export enum EnMove {
  left = "LEFT",
  right = "RIGHT",
  top = "TOP",
  bottom = "BOTTOM",
  DIAGONAL_TOP_LEFT = "DIAGONAL_TOP_LEFT",
  DIAGONAL_TOP_RIGHT = "DIAGONAL_TOP_RIGHT",
  DIAGONAL_BOTTOM_LEFT = "DIAGONAL_BOTTOM_LEFT",
  DIAGONAL_BOTTOM_RIGHT = "DIAGONAL_BOTTOM_RIGHT",
}

export enum Result {
  VERTICAL = "VERTICAL",
  HORIZONTAL = "HORIZONTAL",
  DIAGONAL_LEFT = "DIAGONAL_LEFT",
  DIAGONAL_RIGHT = "DIAGONAL_RIGHT",
}
